name: eHailing EventCatalog

on:
  push:
    branches:
      - main
    paths:
      - "docs/event-catalog/**"
      - ".github/workflows/event-catalog.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: "Deployed site"
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
